### ISSUE TITLE
这个项目还在优化吗？

### ISSUE THREAD

**Issue by zhaofl2015** [Callwoola/pictureCompare#16]
如题，有没有一些可以缓存的中间结果，让查找过程变快。尝试了release版本，但是最新的代码还run不起来。不知道是否还在跟进这个项目哈？

**Comment by Callwoola** [comment]
@zhaofl2015 不好意思没关注这个issue ，一直没有时间优化，不过这是一个现在在运行的项目。有时间我会升级到python3 简化一些冗余代码。

**Comment by codBo** [comment]
这个项目会火🔥
